### ISSUE TITLE
Don't require promise to use create() method

### ISSUE THREAD

**Issue by sdellis** [viewdir/manifesto#27]
Is there a way to use the `create()` method without using `loadManifest()`? I cannot figure out how to do this. Something like: 

```
import manifesto from '../node_modules/manifesto.js/dist/server/manifesto.js'
import manifest from './data/manifest'
const manifestation = manifesto.create(manifest)
```
This results in the following error (manifest is valid and loads fine asynchronously):
```
SyntaxError: Unexpected token u in JSON at position 0
```

There are a number of use cases where this would come in handy, particularly server-side when you have a bunch of manifests on the file system and don't need to fetch externally. It could also be useful in the client for general purposes. I'm currently just working on a prototype to demo managing state with Redux. I have a bunch of fixtures in my code and fetching external data is unnecessary for my purposes.

**Comment by edsilv** [comment]
Needed to JSON.stringify the manifest as it was already in JSON format:

https://runkit.com/edsilv/58e603c6d46e82001487b388
